language: python

python:
 - 2.7
 - 2.6

env:
 - DJANGO_VERSION=1.2.7
 - DJANGO_VERSION=1.3.7
 - DJANGO_VERSION=1.4.8
 - DJANGO_VERSION=1.5.4
 - DJANGO_VERSION=1.6
 - DJANGO_VERSION=1.6.8

install:
  - pip install -q Django==$DJANGO_VERSION

script:
  - cd followit/tests/ && python runtests.py
